language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: kQBwJzvgMYE8hw4japFtRusXVn9wODM4fzIKd243bBVv3FINwgjLkzBZIKCiQ66mJobYwHA1y8fmEAuPBNBkxoRJa0f7XP7YmN82X86Y3ZktgrFEjyOxczr2Favh+gFD+Hhc8YGuKW8idr08QS942RlOtjZGhTlQVO3KP2Qz0aFcxnaYuvs2WmgQhBe49oIa4Nft5nGyizZ7oArH5vQTSGDy9R9XVXPoufci+biAZtvRH18CSHUKe7GlfbJDtVOoA7lE99sZjSj6pHXVN975ZkEptEB+fjBNDNLCVaaRbX9RQDYFkIT6BF4HNZfNz+V4VjW56GObWAHuLWzff8g/MgHeGAXnp/gtKBj9sE7Cv4psV9LvMnBdn90jLL4Poj2vksLv2ZF46uQpI8TuB6GInyP7Uo+TMGfbdqUzyDwqRYARVeKp9UJl32TsGcCS2NkuaH7l6GAsUJaxE83KpAQzzYtoBWLTy9Wlcoitqv6jQgEWZcCglbbK6aDg6Y8kmOEOglNt9acmgy70nUGBfgZojhF4Ozc6JuChRofEEBuHW9A9SZBEmIWMUuxvv65tGhcFoRrLT6hHDtYggO1EZwUdzvrytxlpllO6o92jl6pQcmJxxO7/ONECT0sT0DNyzsnswlHeuOWIPxw6tssp1e+adKYmq/BzQ/C4EIkw1ypL6B8=
  app: pacific-wildwood-70161
  on:
    repo: iamromanh/highlander
