language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Md8vkqTaWfwKFBk98OqGC/ue4y7iLu3r7+9aVc5F5u5W3bAY5owXpIM4bsVO3tOsgVRFYp/62XTk3UwbJ3lZMU8klVy4PvbeR84UGOb0E4iL6wrYe0547rZHvKP8hd2AOw3NSKuI4ka5YTnXZmT9rGFIPALvWOCVUtIQNYtADYT1zwN4aUAEUx87bhK4o+fTOWhe1oeVT65Opizov51jPGjhoPDx6lJBOR97MUGOWN5f8t/0UNb6S8ZAf/MX/UTPsrXs/rA0PprROn1Tv0DTbB1xterYCBoii0kAM8MRCPwNHx1Aiwnywhmq92ADm9bnEGyClu8U6YNbs4n4DXPr4iaSGBhEyMBLTp8jk+H161vRdzf9wL8h3k4wy0C9opDnprv7xfv3cRHxfuTSiUcnAWp4szTuj4E9COds/7TvvjXQTqYwP7UafJM9j5WgO6czYc2ZOtsgTVQptfhry3Shgcp5oIjyaJe9Z9LRHFrtSZcrRUd5RIRx+up8YfzcF0LTfgPN4UysCv1YiecQcqh6ZGGm0NSvzb00DjsOye4j3OswOaem2qADddwrjomDhHXxZS00zQ2mN9osxZKYnJztR6Ku2IrP/4yR2dfcaoy/7ZeGGCb80yp/EoL8jaN0p6J6OTAE7375Dr9wSqH0U4pisPtFt1C+rCg6aJEZO1Uur0M=
  app: pacific-wildwood-70161
  on:
    repo: iamromanh/highlander
