language: node_js
node_js: node
sudo: required
before_install:
  - npm install -g node-gyp
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: BfWP5WJuXPdb07ixJGaKpcgqFnFx+GsTmXZdfrTSmbJ2XDvnIFXx9ZfnFUpSEEO/5TebcIJ+vwmSKnLk69+rypc91/5EgxMMPkoN/xQJEtN8nriNi8WwmOVnbNalo39+VBiBcIOxKQN/leGkv4mHANGYmyxCKQm0Qr65z1GRYcrA3QNrR5DY3dXdUMYNavlkowsSwWa+eoYJEQaZ+hBsebTuPDM7SMZab1iXaJOnR2LI2fWSOB3Q0rRLrO8x7wSsVSayq1ZJ/LCx7WPE2bZBxE0riyZXjbWSzvh2USoMtp+HdfG/h55wkMkksK3atiShR/lSwFkVkMfK4sNZ6Jka8ImNpl6EkLPwRkl2MIV3DTF34Qx9sPVGXzy4T59BxbmDXosA2KqvRF6PijzQ83rTEDRNIgVTx5GQ3QxKEaIMufwhSUTe2DBAJ9uszr9g5ZJ81rBF6LnYj1uWY+k9ZctLh/BQaa9K7hnILDD/MtDbNpt1qsZJlyjLkLANKzYQRd4ika4VALUz1JfY2gd6XCKCNer2Sf+UZWs/xfWOk0JmMKA59yTGe0kj23lzwIF9gh8NKOklKYqV9sRVZR4knedIJJa9czlI8lS0ll4te/hklW9LfEGA6Y1X6LX9NISCJ/OzMQgfbp207PkSD61ECZtQ3OQrFVZeoNMjQkWL8T2C0yw=
  app: highlandersport
  on:
    repo: getromandev/highlander
